platform :ios, '10.0'
inhibit_all_warnings!

use_frameworks!

target 'Pool Scoreboard' do
	pod 'SnapKit',              '~> 5.0'
	pod 'MBProgressHUD',        '~> 1.0'
	pod 'RxSwift',              '~> 5.0'
    pod 'RxCocoa',              '~> 5.0'
    pod 'RxDataSources',        '~> 4.0'
end

def testing_pods
    pod 'Quick'
    pod 'Nimble'
end

target 'Pool ScoreboardTests' do
    testing_pods
end